# Generated by Django 2.0.8 on 2020-01-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0015_auto_20200125_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('DR', 'Draft'), ('PB', 'Published')], default='DR', max_length=20),
        ),
    ]
