# Generated by Django 2.0.8 on 2020-01-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0016_auto_20200125_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('PB', 'Published'), ('DR', 'Draft')], default='DR', max_length=20),
        ),
    ]
