# Generated by Django 2.0.8 on 2020-02-01 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0021_auto_20200126_0451'),
        ('support', '0018_auto_20200130_0303'),
    ]

    operations = [
    ]
