# Generated by Django 2.0.8 on 2020-02-02 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0022_merge_20200201_2352'),
        ('support', '0023_auto_20200130_0225'),
    ]

    operations = [
    ]
