# Generated by Django 2.0.8 on 2020-02-08 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0024_merge_20200202_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('PB', 'Published'), ('DR', 'Draft')], default='DR', max_length=20),
        ),
    ]
