# Generated by Django 2.2.10 on 2020-02-24 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0027_auto_20200223_2246'),
        ('support', '0027_auto_20200213_0147'),
    ]

    operations = [
    ]
