# Generated by Django 2.0.8 on 2020-02-19 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0037_auto_20200215_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('DR', 'Draft'), ('PB', 'Published')], default='DR', max_length=20),
        ),
    ]
