# Generated by Django 2.2.10 on 2020-02-25 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0028_merge_20200224_0016'),
        ('support', '0039_auto_20200220_2259'),
    ]

    operations = [
    ]
