# Generated by Django 2.2.10 on 2020-02-26 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0040_merge_20200225_0244'),
        ('support', '0042_auto_20200226_0407'),
    ]

    operations = [
    ]
