# Generated by Django 2.2.10 on 2020-02-28 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0043_merge_20200226_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('DR', 'Draft'), ('PB', 'Published')], default='DR', max_length=20),
        ),
    ]
