# Generated by Django 2.2.10 on 2020-03-22 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0049_auto_20200318_2137'),
        ('support', '0050_auto_20200320_0034'),
    ]

    operations = [
    ]
