# Generated by Django 2.2.10 on 2020-03-27 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0054_auto_20200327_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('PB', 'Published'), ('DR', 'Draft')], default='DR', max_length=20),
        ),
    ]
