# Generated by Django 2.2.10 on 2020-04-02 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0059_auto_20200329_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('DR', 'Draft'), ('PB', 'Published')], default='DR', max_length=20),
        ),
    ]
