# Generated by Django 2.2.10 on 2020-04-25 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0062_auto_20200424_0226'),
        ('support', '0062_auto_20200409_1937'),
    ]

    operations = [
    ]
