# Generated by Django 2.2.10 on 2020-04-26 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0063_merge_20200425_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('PB', 'Published'), ('DR', 'Draft')], default='DR', max_length=20),
        ),
    ]
