# Generated by Django 2.0.8 on 2019-09-17 00:58

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirConditioning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this item should be treated as active. Unselect this instead of deleting data.')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created time')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='last modified time')),
                ('slug', models.SlugField(editable=False, null=True, unique=True)),
                ('name', models.CharField(help_text='Name must be unique', max_length=200)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('productNumber', models.CharField(max_length=200, null=True)),
                ('price', models.PositiveSmallIntegerField(default=django.utils.timezone.now)),
                ('image', models.ImageField(help_text='All Images must be 800x600px', upload_to='product_images/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this item should be treated as active. Unselect this instead of deleting data.')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created time')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='last modified time')),
                ('name', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(help_text='All Images must be 800x600px', upload_to='product_images/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Furnace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this item should be treated as active. Unselect this instead of deleting data.')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created time')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='last modified time')),
                ('slug', models.SlugField(editable=False, null=True, unique=True)),
                ('name', models.CharField(help_text='Name must be unique', max_length=200)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('productNumber', models.CharField(max_length=200, null=True)),
                ('price', models.PositiveSmallIntegerField(default=django.utils.timezone.now)),
                ('image', models.ImageField(help_text='All Images must be 800x600px', upload_to='product_images/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this item should be treated as active. Unselect this instead of deleting data.')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created time')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='last modified time')),
                ('slug', models.SlugField(editable=False, null=True, unique=True)),
                ('title', models.CharField(help_text='TITLE MUST BE UNIQUE', max_length=200)),
                ('main_header', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('header_1', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('body_1', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('section', models.CharField(blank=True, max_length=10000, null=True)),
                ('header_2', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('body_2', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this item should be treated as active. Unselect this instead of deleting data.')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created time')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='last modified time')),
                ('slug', models.SlugField(editable=False, null=True, unique=True)),
                ('name', models.CharField(help_text='Name must be unique', max_length=200)),
                ('image', models.ImageField(help_text='All Images must be 800x600px', upload_to='product_images/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this item should be treated as active. Unselect this instead of deleting data.')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created time')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='last modified time')),
                ('date', models.DateField(null=True)),
                ('name', models.CharField(max_length=35, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('people', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10+')], db_index=True, default=None)),
                ('reservation_time', models.PositiveSmallIntegerField(choices=[(1, '4:00pm'), (2, '4:30pm'), (3, '5:00pm'), (4, '5:30pm'), (5, '6:00pm'), (6, '6:30pm'), (7, '7:00pm'), (8, '7:30pm'), (9, '8:00pm')], db_index=True, default=None)),
            ],
            options={
                'verbose_name_plural': 'Reservations',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this item should be treated as active. Unselect this instead of deleting data.')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created time')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='last modified time')),
                ('description', models.CharField(max_length=256)),
                ('customer', models.CharField(help_text='Customer first and last name', max_length=256)),
                ('city', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this item should be treated as active. Unselect this instead of deleting data.')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created time')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='last modified time')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=256)),
                ('image', models.ImageField(help_text='All Images must be 800x600px', upload_to='product_images/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
