# Generated by Django 2.0.8 on 2018-10-23 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_courseselectpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopage',
            name='grade',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
