# Generated by Django 2.0.8 on 2018-11-09 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('home', '0004_videopage_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseselectpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='videocontentpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='videopage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='CourseSelectPage',
        ),
        migrations.DeleteModel(
            name='VideoContentPage',
        ),
        migrations.DeleteModel(
            name='VideoPage',
        ),
    ]
