# Generated by Django 2.0.8 on 2019-01-13 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190113_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutpage',
            old_name='paragraph_one',
            new_name='body_five',
        ),
        migrations.RenameField(
            model_name='aboutpage',
            old_name='paragraph_two',
            new_name='header_five',
        ),
    ]
