# Generated by Django 2.0.8 on 2019-01-26 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20190113_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='video_thumbnail',
            field=models.CharField(blank=True, help_text='Upload a JPG', max_length=250, null=True),
        ),
    ]
