# Generated by Django 2.0.8 on 2019-01-27 00:40

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_aboutpage_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacypage',
            name='content',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='termspage',
            name='content',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
