# Generated by Django 2.0.8 on 2019-01-27 00:51

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20190127_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacypage',
            name='header',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='termspage',
            name='header',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
