# Generated by Django 2.0.8 on 2019-02-11 23:04

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20190127_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='mainbody',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='mainheader',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
