# Generated by Django 2.0.8 on 2019-02-11 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20190211_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='mainbody',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='mainheader',
        ),
    ]
