# Generated by Django 2.0.8 on 2019-02-11 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20190211_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='firstbody',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='firstheader',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
