# Generated by Django 2.0.8 on 2019-02-11 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20190211_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='firstbody',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='firstheader',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
