# Generated by Django 2.0.8 on 2019-02-15 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20190211_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='firstheader',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
