# Generated by Django 2.0.8 on 2019-02-23 02:41

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('home', '0017_auto_20190215_0403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='page_ptr',
        ),
        migrations.AddField(
            model_name='formpage',
            name='address',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='formpage',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.DeleteModel(
            name='ContactPage',
        ),
    ]
