# Generated by Django 2.0.8 on 2019-02-23 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20190223_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formpage',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='formpage',
            name='body',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
