# Generated by Django 2.0.8 on 2019-02-23 03:14

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20190223_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formpage',
            name='address',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='formpage',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
