# Generated by Django 2.0.8 on 2019-04-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20190223_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='firstbody',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='firstheader',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
