# Generated by Django 2.0.8 on 2019-05-17 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20190430_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='firstbody',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='firstheader',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='registerbuttonurl',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
