# Generated by Django 2.0.8 on 2019-08-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_servicespage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicespage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='servicespage',
            name='body_two',
        ),
        migrations.RemoveField(
            model_name='servicespage',
            name='header',
        ),
        migrations.RemoveField(
            model_name='servicespage',
            name='header_two',
        ),
        migrations.AddField(
            model_name='servicespage',
            name='firstbody',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='firstheader',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='secondbody',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='secondheader',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
