# Generated by Django 2.0.8 on 2019-08-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20190804_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicespage',
            name='fourthbody',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='fourthheader',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='thirdbody',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='thirdheader',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
