# Generated by Django 2.0.8 on 2019-08-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20190804_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicespage',
            name='secondbody_2',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
