# Generated by Django 2.0.8 on 2019-08-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_servicespage_secondbody_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicespage',
            name='thirdbody_2',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
