# Generated by Django 2.0.8 on 2019-08-31 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_servicespage_thirdbody_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='video_thumbnail',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='video_url',
        ),
    ]
