# Generated by Django 2.0.8 on 2020-01-18 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(blank=True, max_length=50)),
                ('plan_id', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
