# Generated by Django 2.0.8 on 2020-01-18 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
