# Generated by Django 2.0.8 on 2020-01-19 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20200118_2357'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Plan',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='name',
            new_name='nickname',
        ),
    ]
