# Generated by Django 2.0.8 on 2020-01-19 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20200119_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='amount',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='plan',
            name='currency',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='plan',
            name='interval',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
