# Generated by Django 2.0.8 on 2020-01-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_auto_20200119_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='slug',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
