# Generated by Django 2.0.8 on 2020-01-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='slug',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
