# Generated by Django 2.0.8 on 2020-01-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_subscription_plan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='payment_intent_status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
