# Generated by Django 2.0.8 on 2020-01-26 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_subscription_subscription_item_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Describe a benefit of the subscription product.', max_length=36)),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='description',
            field=models.CharField(default='add description', max_length=255),
        ),
        migrations.AlterField(
            model_name='plan',
            name='amount',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='plan',
            name='currency',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='plan',
            name='interval',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='plan',
            name='nickname',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='plan',
            name='product_id',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='plan',
            name='slug',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='plan',
            name='benefit',
            field=models.ManyToManyField(to='payments.Benefit'),
        ),
    ]
