# Generated by Django 2.0.8 on 2020-01-30 02:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_auto_20200126_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subscription_quantity',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
