# Generated by Django 2.0.8 on 2020-02-11 03:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0016_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemd_at', models.DateTimeField(default=datetime.datetime(2020, 2, 11, 3, 17, 45, 412191, tzinfo=utc))),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo', to='payments.Coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
