# Generated by Django 2.0.8 on 2020-02-11 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_auto_20200211_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promouser',
            name='promotion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promo', to='payments.Coupon'),
        ),
        migrations.AlterField(
            model_name='promouser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promo_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
