# Generated by Django 2.0.8 on 2020-02-11 23:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0020_coupon_times_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='times_used',
        ),
        migrations.AddField(
            model_name='promouser',
            name='times_used',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
