# Generated by Django 2.0.8 on 2020-02-12 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0021_auto_20200211_2301'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coupon',
            new_name='Promotion',
        ),
    ]
