# Generated by Django 2.0.8 on 2020-02-15 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0022_auto_20200212_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promouser',
            name='times_used',
        ),
        migrations.AddField(
            model_name='promouser',
            name='has_used',
            field=models.BooleanField(default=False),
        ),
    ]
