# Generated by Django 2.0.8 on 2020-02-15 00:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0023_auto_20200215_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='trial_period',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
