# Generated by Django 2.0.8 on 2020-02-15 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0024_promotion_trial_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='payment_intent_status',
        ),
    ]
