# Generated by Django 2.0.8 on 2020-02-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0031_promotion_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='payment_status',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
    ]
