# Generated by Django 2.0.8 on 2020-02-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0033_auto_20200225_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='slug',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
