# Generated by Django 2.0.8 on 2020-02-26 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0034_auto_20200225_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='latest_invoice_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment_status',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
