# Generated by Django 2.0.8 on 2020-02-26 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0036_auto_20200226_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='unix_trial_end',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='unix_trial_start',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
