# Generated by Django 2.2.10 on 2020-03-20 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0039_auto_20200319_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Canceled At'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='unix_canceled_at',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
