# Generated by Django 2.2.10 on 2020-03-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0040_auto_20200320_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='latest_invocie_url',
            field=models.URLField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='subscription',
            name='latest_invoice_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='subscription',
            name='latest_receipt_url',
            field=models.URLField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='latest_invoice_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment_status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
