# Generated by Django 2.2.10 on 2020-03-29 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0041_auto_20200329_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='latest_invocie_url',
            new_name='latest_invoice_url',
        ),
    ]
