# Generated by Django 2.2.10 on 2020-03-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0043_subscription_latest_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='invoice_upcoming',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
