# Generated by Django 2.0.8 on 2019-11-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_remove_address_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='downloadable_content',
        ),
        migrations.AddField(
            model_name='merchant',
            name='downloadable_content_title',
            field=models.CharField(blank=True, help_text='Examples: menu, brochure, etc.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='downloadable_content_url',
            field=models.CharField(blank=True, help_text='Link to AWS download url goes here', max_length=500, null=True),
        ),
    ]
