# Generated by Django 2.0.8 on 2019-11-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_auto_20191130_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='ref_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
