# Generated by Django 2.0.8 on 2019-12-04 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_auto_20191130_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='banner',
            field=models.ImageField(null=True, upload_to='merchant-banners/'),
        ),
    ]
