# Generated by Django 2.0.8 on 2019-12-06 01:51

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_auto_20191204_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='Longititude',
            field=models.IntegerField(blank=True, help_text="Enter longitude of merchant's location.", null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='lattitude',
            field=models.IntegerField(blank=True, help_text="Enter lattitude of merchant's location.", null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
