# Generated by Django 2.0.8 on 2019-12-06 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_auto_20191206_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='Longititude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text="Enter longitude of merchant's location.", max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='lattitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text="Enter lattitude of merchant's location.", max_digits=11, null=True),
        ),
    ]
