# Generated by Django 2.0.8 on 2019-12-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_auto_20191207_0633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='video_url',
        ),
        migrations.AddField(
            model_name='merchant',
            name='promotional_video_file_name',
            field=models.CharField(blank=True, help_text='Name of the file uploaded to Amazon S3 Bucket. (ie: Video.MP4)', max_length=1000),
        ),
    ]
