# Generated by Django 2.0.8 on 2019-12-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0023_subcategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('FOOD', 'Food & Dining'), ('DEALERSHIP', 'Automotive & Transportation')], db_index=True, default='Food', max_length=20, unique=True),
        ),
    ]
