# Generated by Django 2.0.8 on 2019-12-10 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0026_auto_20191207_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='portal.Address'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='about',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about', to='portal.About'),
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='address',
        ),
        migrations.AddField(
            model_name='merchant',
            name='address',
            field=models.ManyToManyField(blank=True, null=True, related_name='merchant', to='portal.Address'),
        ),
    ]
