# Generated by Django 2.0.8 on 2019-12-14 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_auto_20191214_1943'),
        ('portal', '0033_auto_20191214_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='address',
            field=models.ManyToManyField(related_name='merchant', to='location.Address'),
        ),
        migrations.AddField(
            model_name='offer',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='location.Address'),
        ),
    ]
