# Generated by Django 2.0.8 on 2019-12-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0036_auto_20191220_0206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='tag',
        ),
        migrations.AddField(
            model_name='offer',
            name='code_coupon',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
