# Generated by Django 2.0.8 on 2019-12-17 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0037_auto_20191217_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Context', verbose_name='Context'),
        ),
    ]
