# Generated by Django 2.0.8 on 2019-12-23 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0039_auto_20191219_0351'),
        ('portal', '0036_auto_20191220_0206'),
    ]

    operations = [
    ]
