# Generated by Django 2.0.8 on 2019-12-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0040_remove_merchant_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('FOOD', 'Food & Dining'), ('VEHICLES', 'Automotive & Transportation'), ('HOME', 'Home Improvement')], db_index=True, default='FOOD', max_length=20, unique=True),
        ),
    ]
