# Generated by Django 2.0.8 on 2019-12-29 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0040_merge_20191223_1733'),
        ('portal', '0041_auto_20191226_2051'),
    ]

    operations = [
    ]
