# Generated by Django 2.0.8 on 2020-01-04 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0041_auto_20200104_0355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='ref_code',
        ),
    ]
