# Generated by Django 2.0.8 on 2019-12-29 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0042_merge_20191229_0012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'Subcategories'},
        ),
        migrations.AddField(
            model_name='merchant',
            name='code_coupon',
            field=models.CharField(blank=True, help_text='NOTE: Leave blank and a GEGOO coupon code will be generated', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='ref_code',
            field=models.CharField(blank=True, default='0000', editable=False, max_length=20),
        ),
    ]
