# Generated by Django 2.0.8 on 2019-12-30 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0044_auto_20191229_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchant',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='facebook_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='website_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
