# Generated by Django 2.0.8 on 2020-01-04 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0042_remove_merchant_ref_code'),
        ('portal', '0045_auto_20191230_0438'),
    ]

    operations = [
    ]
