# Generated by Django 2.0.8 on 2020-01-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0046_merge_20200104_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
