# Generated by Django 2.0.8 on 2019-02-19 00:21

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20190219_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectindexpage',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectindexpage',
            name='header',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
