# Generated by Django 2.0.8 on 2019-02-19 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20190219_0021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectpage',
            old_name='registerbuttonurl',
            new_name='url',
        ),
    ]
