# Generated by Django 2.0.8 on 2019-02-19 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20190219_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='image_url',
            field=models.CharField(blank=True, help_text='Image link', max_length=250),
        ),
    ]
