# Generated by Django 2.0.8 on 2019-02-19 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_projectpage_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpage',
            name='url',
        ),
    ]
