# Generated by Django 2.0.8 on 2019-02-19 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_remove_projectpage_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='url',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
