# Generated by Django 2.0.8 on 2019-02-19 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20190219_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='work_done',
            field=models.CharField(default='UI / UX Design &middot; Web Development', max_length=250),
        ),
    ]
