# Generated by Django 2.0.8 on 2019-02-20 03:33

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_projectpage_work_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='header',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='title_body',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
