# Generated by Django 2.0.8 on 2019-02-21 00:31

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_auto_20190220_0333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectpage',
            old_name='body',
            new_name='body_1',
        ),
        migrations.RenameField(
            model_name='projectpage',
            old_name='title_body',
            new_name='title_1',
        ),
        migrations.AddField(
            model_name='projectpage',
            name='body_2',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='body_3',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='title_2',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='title_3',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
