# Generated by Django 2.0.8 on 2019-02-21 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20190221_0031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectpage',
            old_name='image_url',
            new_name='image_url_1',
        ),
        migrations.AddField(
            model_name='projectpage',
            name='image_url_2',
            field=models.CharField(blank=True, help_text='Image link', max_length=250),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='image_url_3',
            field=models.CharField(blank=True, help_text='Image link', max_length=250),
        ),
    ]
