# Generated by Django 2.0.8 on 2019-02-23 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20190221_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='work_done',
            field=models.CharField(default='UI / UX Design • Web Development', max_length=250),
        ),
    ]
