# Generated by Django 2.0.8 on 2019-02-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_auto_20190223_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
