# Generated by Django 2.0.8 on 2019-07-26 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_projectpage_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpage',
            name='header',
        ),
        migrations.AddField(
            model_name='projectpage',
            name='image_url_thumbnail',
            field=models.CharField(blank=True, help_text='Image link', max_length=250),
        ),
    ]
