# Generated by Django 2.0.8 on 2020-01-12 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_paid',
            field=models.BooleanField(default=False, verbose_name='PaymentStatus'),
        ),
    ]
