# Generated by Django 2.0.8 on 2020-01-16 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchantprofile',
            old_name='has_paid',
            new_name='payment_status',
        ),
    ]
