# Generated by Django 2.0.8 on 2020-01-19 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchantprofile',
            old_name='stripe_id',
            new_name='customer_id',
        ),
    ]
