# Generated by Django 2.0.8 on 2020-01-16 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200116_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantprofile',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
