# Generated by Django 2.0.8 on 2018-11-09 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181018_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='merchandise',
        ),
    ]
