# Generated by Django 2.0.8 on 2020-01-29 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200119_0130'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='merchantprofile',
        #     name='business_name',
        # ),
        # migrations.RemoveField(
        #     model_name='merchantprofile',
        #     name='description',
        # ),
        # migrations.RemoveField(
        #     model_name='merchantprofile',
        #     name='has_paid',
        # ),
    ]
