# Generated by Django 2.0.8 on 2020-01-29 21:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200129_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='stores',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
