# Generated by Django 2.0.8 on 2020-01-12 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200109_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending Approval'), ('NOT APPROVED', 'Not Approved')], default='NOT APPROVED', max_length=20),
        ),
    ]
