# Generated by Django 2.0.8 on 2020-01-18 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantprofile',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending Approval'), ('NOT APPROVED', 'Not Approved'), ('DENIED', 'Denied')], default='NOT APPROVED', max_length=20),
        ),
    ]
