# Generated by Django 2.0.8 on 2020-02-02 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200118_0104'),
        ('users', '0004_merchantprofile_stores'),
    ]

    operations = [
    ]
