# Generated by Django 2.0.8 on 2019-01-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0037_auto_20190126_0046'),
        ('users', '0005_auto_20190116_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='enrolled',
            field=models.ManyToManyField(related_name='profile', to='portal.Course'),
        ),
    ]
