# Generated by Django 2.0.8 on 2020-01-13 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0008_city_timezone'),
        ('users', '0005_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending Approval'), ('NOT APPROVED', 'Not Approved')], default='NOT APPROVED', max_length=20)),
                ('has_paid', models.BooleanField(default=False, verbose_name='payment_status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated at')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchant_city', to='cities_light.City')),
            ],
        ),
        migrations.RemoveField(
            model_name='userstripe',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='has_paid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_city', to='cities_light.City'),
        ),
        migrations.DeleteModel(
            name='userStripe',
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
