# Generated by Django 2.0.8 on 2020-01-30 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200118_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantprofile',
            name='description',
        ),
    ]
