# Generated by Django 2.0.8 on 2020-02-02 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_merge_20200202_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantprofile',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='merchantprofile',
            name='description',
        ),
    ]
