# Generated by Django 2.0.8 on 2020-02-01 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200119_0130'),
        ('users', '0006_remove_merchantprofile_description'),
    ]

    operations = [
    ]
