# Generated by Django 2.0.8 on 2019-01-27 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_enrolled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.CharField(blank=True, default='Stemletics University', max_length=30),
        ),
    ]
