# Generated by Django 2.0.8 on 2020-01-14 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200114_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantprofile',
            name='facebook_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='merchantprofile',
            name='website_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
