# Generated by Django 2.0.8 on 2019-01-30 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190127_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='enrolled',
            field=models.ManyToManyField(blank=True, related_name='profile', to='portal.Course'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='blankImage.png', null=True, upload_to=users.models.upload_to, verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name_of_User'),
        ),
    ]
