# Generated by Django 2.2.10 on 2020-02-25 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_follow'),
        ('users', '0008_auto_20200208_0141'),
    ]

    operations = [
    ]
