# Generated by Django 2.0.8 on 2019-02-14 23:54

import django.core.validators
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190130_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='blankImage.png', help_text='Image must be a .PNG or .JPG', null=True, upload_to=users.models.upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])], verbose_name='Picture'),
        ),
    ]
