# Generated by Django 2.0.8 on 2020-01-03 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200103_0206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstripe',
            name='user',
        ),
        migrations.DeleteModel(
            name='userStripe',
        ),
    ]
