# Generated by Django 2.2.10 on 2020-03-26 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_user_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantprofile',
            name='status',
            field=models.CharField(choices=[('INITIAL', 'Initial'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Not Approved'), ('DENIED', 'Denied')], default='INITIAL', max_length=20),
        ),
    ]
