# Generated by Django 2.2.10 on 2020-03-27 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200326_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantprofile',
            name='status',
            field=models.CharField(choices=[('INITIAL', 'Initial'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('DENIED', 'Denied')], default='INITIAL', max_length=20),
        ),
    ]
