# Generated by Django 2.0.8 on 2020-01-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200103_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='user',
            name='has_paid',
            field=models.BooleanField(default=False, verbose_name='Payment_status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Merchant_is_approved'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_merchant',
            field=models.BooleanField(default=False, verbose_name='User_is_merchant'),
        ),
    ]
