# Generated by Django 2.2.10 on 2020-04-24 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200327_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='content_uploaded',
            field=models.BooleanField(default=False, verbose_name='Has this user uploaded content?'),
        ),
    ]
