AWS_UPLOAD_BUCKET = 'upload-gegoo-bucket-s4-frankfurt'

AWS_UPLOAD_USERNAME = 'gegoo-upload-user'

AWS_UPLOAD_GROUP = 'CFE_Gegoo_group'

AWS_UPLOAD_REGION = 'eu-central-1'

AWS_UPLOAD_ACCESS_KEY_ID = 'AKIAXTP3WIX7MNEWDPUS'

AWS_UPLOAD_SECRET_KEY = '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'

AWS_S3_SIGNATURE_VERSION = 's3v4'
