version: '2'

# -------------- Volumes -----------------

volumes:
  postgres_data: {}
  postgres_backup: {}
  esdata1:
    driver: local
  esdata2:
    driver: local

services:
# -------------- DJANGO -----------------
  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    #command: gunicorn mysite.wsgi:application --bind 0.0.0.0:8000 --chdir=/app --log-level=info --log-file=./logs/gunicorn.log --access-logfile=./logs/gunicorn-access.log
    depends_on:
      - postgres
    #environment:
    #  - POSTGRES_USER=reliable_carriers
    #  - USE_DOCKER=yes
    env_file:
      #- ./envs/common/django.env
      - ./env
    volumes:
      - .:/app
    expose:
      - 8000
    links:
      - postgres
      - elasticsearch
    networks:
      - database1_network
      - nginx_network
      - elastic_network


# -------------- Postgres -----------------
  postgres:
    build:
      context: .
      dockerfile: ./compose/postgres/Dockerfile
    # build:
    #   context: .
    #   dockerfile: ./compose/postgres/Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    ports:
      - 5432:5432
    env_file:
        - ./compose/postgres/postgres.env
    networks:
      - database1_network
    # environment:
      # - POSTGRES_USER=gegooadmin
      # - POSTGRES_PASSWORD=$Django10
      # - POSTGRES_PORT=
    #

# -------------- Elastic Search -----------------
  elasticsearch:
    build:
      context: .
      dockerfile: ./compose/elastic/Dockerfile
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    network.host: 0.0.0.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic_network

# -------------- NGINX -----------------
  nginx:
    build:
        context: .
        dockerfile: ./compose/nginx/Dockerfile
    command: [nginx-debug, -g, daemon off;]
    ports:
      - 80:80 #Map TCP port 80 in the container to port 8000 on the Docker host.
      - 443:443
    depends_on:
      - django
    networks:
      - nginx_network



# -------------- Networks -----------------

networks:
  database1_network:
    driver: bridge
  nginx_network:
    driver: bridge
  elastic_network:
    driver: bridge
