# Generated by Django 2.0.8 on 2020-01-20 03:27

import django.core.validators
from django.db import migrations, models
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_videofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='file',
            field=models.FileField(help_text='Image must be a .MP4 or .MOV', upload_to=files.models.update_filename, validators=[django.core.validators.FileExtensionValidator(['mp4', 'mov'])]),
        ),
    ]
