# Generated by Django 2.0.8 on 2020-01-24 02:57

import django.core.validators
from django.db import migrations, models
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20200120_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videofile',
            name='file',
            field=models.FileField(help_text='Image must be a .MP4 or .MOV', upload_to=files.models.update_filename, validators=[django.core.validators.FileExtensionValidator(['mp4', 'mov']), files.models.file_size]),
        ),
    ]
