# Generated by Django 2.0.8 on 2020-02-01 06:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_auto_20200125_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionalVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('active', models.BooleanField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
            ],
        ),
        migrations.RemoveField(
            model_name='videofile',
            name='user',
        ),
        migrations.AddField(
            model_name='promotionalvideo',
            name='video',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='files.VideoFile'),
        ),
    ]
