# Generated by Django 2.0.8 on 2020-02-01 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_auto_20200201_0614'),
        ('files', '0006_auto_20200201_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='store',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videofile', to='portal.Store'),
        ),
    ]
