# Generated by Django 2.2.10 on 2020-03-11 00:00

import django.core.validators
from django.db import migrations, models
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_auto_20200208_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videofile',
            name='file',
            field=models.FileField(help_text='Image must be a .MP4 or .MOV', max_length=255, upload_to=files.models.update_filename, validators=[django.core.validators.FileExtensionValidator(['mp4', 'mov']), files.models.file_size]),
        ),
    ]
