# Generated by Django 2.2.10 on 2020-04-24 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0010_auto_20200424_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefile',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='videofile',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
