# Generated by Django 2.2.10 on 2020-04-24 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0011_auto_20200424_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagefile', to='portal.Store'),
        ),
    ]
