# Generated by Django 2.2.10 on 2020-04-24 23:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0046_auto_20200423_2158'),
        ('files', '0012_auto_20200424_0231'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadableFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(help_text='File must be PDF, ZIP, or PowerPoint', max_length=255, upload_to=files.models.update_filename, validators=[django.core.validators.FileExtensionValidator(['pdf', 'zip', 'ppt', 'pptx']), files.models.file_size])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('store', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downloadablefile', to='portal.Store')),
            ],
        ),
        migrations.AlterField(
            model_name='videofile',
            name='file',
            field=models.FileField(help_text='Image must be a .MP4 or .MOV', max_length=255, upload_to=files.models.update_filename, validators=[django.core.validators.FileExtensionValidator(['mp4', 'mov']), files.models.file_size]),
        ),
        migrations.DeleteModel(
            name='FileItem',
        ),
    ]
