# Generated by Django 2.2.10 on 2020-04-25 23:47

import django.core.validators
from django.db import migrations, models
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0013_auto_20200424_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadablefile',
            name='file',
            field=models.FileField(help_text='File must be PDF, ZIP, or PowerPoint', max_length=255, upload_to=files.models.update_downloadable_filename, validators=[django.core.validators.FileExtensionValidator(['pdf', 'zip', 'ppt', 'pptx']), files.models.file_size]),
        ),
    ]
