# Generated by Django 2.0.8 on 2019-12-06 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_auto_20191206_0157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchant',
            old_name='Longititude',
            new_name='Longitude',
        ),
    ]
