# Generated by Django 2.0.8 on 2019-12-11 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0028_auto_20191210_0240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='main_image',
            new_name='image',
        ),
    ]
