# Generated by Django 2.0.8 on 2019-12-19 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0038_faq_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='context',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Context', verbose_name='Context'),
        ),
    ]
