# Generated by Django 2.0.8 on 2019-12-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0043_auto_20191229_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='id',
        ),
        migrations.AlterField(
            model_name='merchant',
            name='ref_code',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
