# Generated by Django 2.0.8 on 2018-11-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_auto_20181103_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('BASIC', 'Basic'), ('PREMIUM', 'Premium'), ('FREE', 'Free')], default='FREE', max_length=30),
        ),
    ]
