# Generated by Django 2.0.8 on 2020-01-15 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_auto_20200115_0111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='image',
        ),
    ]
