# Generated by Django 2.0.8 on 2018-11-09 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0004_auto_20181103_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Premium', 'Premium'), ('Enterprise', 'Enterprise')], default='Basic', max_length=30),
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='membership',
            field=models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.SET_NULL, to='memberships.Membership'),
        ),
    ]
