# Generated by Django 2.0.8 on 2018-11-10 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0006_auto_20181110_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='stripe_price',
            field=models.IntegerField(default=15),
        ),
    ]
