# Generated by Django 2.0.8 on 2018-11-10 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0007_membership_stripe_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
