# Generated by Django 2.0.8 on 2018-11-10 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0008_auto_20181110_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='stripe_price',
        ),
    ]
