# Generated by Django 2.0.8 on 2018-11-10 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0010_membership_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
