# Generated by Django 2.0.8 on 2018-11-11 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0011_membership_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='total',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='membership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_membership', to='memberships.Membership'),
        ),
    ]
