# Generated by Django 2.0.8 on 2018-11-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0012_auto_20181111_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
