# Generated by Django 2.0.8 on 2018-11-15 03:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0017_auto_20181115_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='order_id',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=36, unique=True),
        ),
    ]
