# Generated by Django 2.0.8 on 2018-11-15 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0018_auto_20181115_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='memberships.Membership'),
        ),
    ]
