# Generated by Django 2.0.8 on 2018-11-15 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0021_auto_20181115_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='membership',
        ),
        migrations.AddField(
            model_name='transaction',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_transaction', to='memberships.Subscription'),
        ),
    ]
