# Generated by Django 2.0.8 on 2018-11-17 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0023_auto_20181115_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='user_membership',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='memberships.UserMembership'),
        ),
    ]
