# Generated by Django 2.0.8 on 2018-11-25 01:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0024_auto_20181117_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermembership',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_usermembership', to=settings.AUTH_USER_MODEL),
        ),
    ]
