# Generated by Django 2.0.8 on 2018-12-01 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0025_auto_20181125_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='total',
        ),
    ]
