# Generated by Django 2.0.8 on 2018-12-01 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0027_membership_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='total',
        ),
    ]
