# Generated by Django 2.0.8 on 2018-12-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0030_auto_20181201_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
