# Generated by Django 2.0.8 on 2019-02-24 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0032_auto_20190113_0130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36)),
            ],
        ),
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Website Hosting', 'Website Hosting'), ('PPC Advertising', 'PPC Advertising'), ('SEO', 'SEO')], default='Website Hosting', max_length=30),
        ),
        migrations.AddField(
            model_name='membership',
            name='benefit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='memberships.Benefit'),
        ),
    ]
