# Generated by Django 2.0.8 on 2019-02-24 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0033_auto_20190224_0319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='benefit',
        ),
        migrations.AddField(
            model_name='membership',
            name='benefit',
            field=models.ManyToManyField(null=True, to='memberships.Benefit'),
        ),
    ]
