# Generated by Django 2.0.8 on 2019-02-24 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0035_auto_20190224_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='description',
            field=models.CharField(default='add description', max_length=255),
        ),
    ]
