# Generated by Django 2.0.8 on 2019-02-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0036_membership_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='special',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Website Hosting', 'Website Hosting'), ('PPC Advertising', 'PPC Advertising'), ('Digital Marketing', 'Digital Marketing')], default='Website Hosting', max_length=30),
        ),
    ]
