# Generated by Django 2.0.8 on 2019-03-02 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memberships', '0037_auto_20190224_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('slug', models.SlugField()),
                ('invoice_id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('payed', models.BooleanField(default=False, help_text='Has the customer payed?')),
                ('description', models.CharField(default='add description', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
