# Generated by Django 2.0.8 on 2019-03-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0038_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='date_due',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='date_issued',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
