# Generated by Django 2.0.8 on 2019-03-02 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0039_auto_20190302_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='price',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='image',
        ),
    ]
