# Generated by Django 2.0.8 on 2019-03-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0042_auto_20190302_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date_issued',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
