# Generated by Django 2.0.8 on 2019-03-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0044_auto_20190302_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
