# Generated by Django 2.0.8 on 2019-03-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0045_auto_20190302_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='charge',
        ),
        migrations.AddField(
            model_name='invoice',
            name='charge',
            field=models.ManyToManyField(to='memberships.Charge'),
        ),
    ]
