# Generated by Django 2.0.8 on 2019-03-03 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0046_auto_20190302_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
