# Generated by Django 2.0.8 on 2019-03-09 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0047_transaction_invoice_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('-issue_date', 'due_date'), 'verbose_name': 'Invoice', 'verbose_name_plural': 'Invoices'},
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='date_due',
            new_name='due_date',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='date_issued',
            new_name='issue_date',
        ),
    ]
