# Generated by Django 2.0.8 on 2019-05-21 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0050_membership_stripe_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='stripe_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
