# Generated by Django 2.0.8 on 2019-08-30 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0053_auto_20190726_0111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='special',
        ),
        migrations.AlterField(
            model_name='membership',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
