# Generated by Django 2.0.8 on 2019-08-30 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0054_auto_20190830_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='position',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
