# Generated by Django 2.0.8 on 2019-08-30 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0055_auto_20190830_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
