# Generated by Django 2.2 on 2019-10-23 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0002_auto_20191023_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('B', 'Billing'), ('S', 'Shipping')], default='AL', max_length=100),
        ),
    ]
