# Generated by Django 2.2 on 2019-11-03 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0004_auto_20191025_0009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-ordered_date']},
        ),
    ]
