# Generated by Django 2.2 on 2019-11-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0005_auto_20191103_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('A', 'ATTENTION NEEDED'), ('P', 'PROCESSING'), ('D', 'DELIVERED'), ('S', 'SHIPPED')], default='P', max_length=1),
        ),
    ]
