# Generated by Django 2.2 on 2019-11-03 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0007_auto_20191103_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('A', 'ATTENTION NEEDED'), ('P', 'PROCESSING'), ('D', 'DELIVERED'), ('S', 'SHIPPED')], default='P', max_length=1),
        ),
    ]
