# Generated by Django 2.2 on 2019-11-03 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0008_auto_20191103_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='arrival_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
