# Generated by Django 2.0.8 on 2019-11-09 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0011_auto_20191109_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
    ]
