# Generated by Django 2.0.8 on 2019-11-09 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0015_auto_20191109_1924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
