# Generated by Django 2.0.8 on 2019-11-10 17:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0017_item_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(help_text='Image must be a .PNG or .JPG', upload_to='photos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('main_photo', models.BooleanField()),
            ],
        ),
    ]
