# Generated by Django 2.0.8 on 2019-11-10 19:30

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0019_auto_20191110_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
