# Generated by Django 2.0.8 on 2019-11-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0020_auto_20191110_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='main_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='images',
            field=models.ManyToManyField(blank=True, help_text='Alternate Photos of Product', to='shoppingcart.Image'),
        ),
    ]
