# Generated by Django 2.0.8 on 2019-11-16 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0021_auto_20191110_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='email',
        ),
        migrations.AddField(
            model_name='refund',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='main_image',
            field=models.ImageField(null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='reason',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], max_length=1),
        ),
    ]
