# Generated by Django 2.0.8 on 2019-11-22 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0022_auto_20191116_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=64)),
                ('background_color', models.CharField(max_length=10)),
                ('active', models.BooleanField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
