# Generated by Django 2.0.8 on 2019-11-22 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0023_promotion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='background_color',
        ),
        migrations.AddField(
            model_name='promotion',
            name='background',
            field=models.CharField(choices=[('Primary', 'bg-primary'), ('Secondary', 'bg-secondary'), ('Alternate', 'bg-alt')], default='Primary', max_length=12),
        ),
    ]
