# Generated by Django 2.0.8 on 2019-12-05 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='merchant_select',
            field=models.CharField(choices=[('NO', 'No'), ('YES', 'Yes')], default='NO', max_length=2),
        ),
    ]
