# Generated by Django 2.0.8 on 2019-12-11 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191210_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ip_address',
            field=models.CharField(default='ABC', max_length=120),
        ),
    ]
