# Generated by Django 2.0.8 on 2019-12-14 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
    ]
