# Generated by Django 2.0.8 on 2020-01-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20191215_0539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='profile',
            name='points',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
