# Generated by Django 2.0.8 on 2020-01-04 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200103_2052'),
        ('users', '0008_auto_20200104_1733'),
    ]

    operations = [
    ]
