# Generated by Django 2.0.8 on 2020-01-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_merge_20200104_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_paid',
            field=models.BooleanField(default=False, verbose_name='payment_status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='merchant_is_approved'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_merchant',
            field=models.BooleanField(default=False, verbose_name='is_merchant'),
        ),
    ]
