# Generated by Django 2.0.8 on 2019-12-15 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
