# Generated by Django 2.0.8 on 2019-12-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_delete_testmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='reason',
            field=models.CharField(choices=[('QT', 'I have a Question'), ('DS', 'Dissatisfied with a Coupon'), ('BM', 'I Would Like to post my own Coupons')], default='QT', max_length=100),
        ),
    ]
