# Generated by Django 2.0.8 on 2020-01-04 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20191226_2009'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
