# Generated by Django 2.0.8 on 2020-01-15 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store_address',
            name='store',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_address', to='portal.Store'),
        ),
    ]
