# Generated by Django 2.0.8 on 2020-01-08 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0008_city_timezone'),
        ('location', '0002_auto_20200104_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='store_address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=100, null=True)),
                ('apartment_address', models.CharField(blank=True, max_length=100, null=True)),
                ('zip', models.CharField(max_length=100, null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.City')),
            ],
            options={
                'verbose_name_plural': 'store_addresses',
            },
        ),
        migrations.RemoveField(
            model_name='merchant_address',
            name='city',
        ),
        migrations.RemoveField(
            model_name='merchant_address',
            name='merchant',
        ),
        migrations.DeleteModel(
            name='Merchant_Address',
        ),
    ]
