# Generated by Django 2.0.8 on 2020-01-09 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_store_address_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='city',
        ),
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
