# Generated by Django 2.0.8 on 2020-01-17 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_auto_20200116_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storelocation',
            name='store',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_location', to='portal.Store'),
        ),
    ]
