# Generated by Django 2.0.8 on 2020-02-02 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_auto_20200117_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storelocation',
            name='city',
        ),
        migrations.RemoveField(
            model_name='storelocation',
            name='store',
        ),
        migrations.DeleteModel(
            name='StoreLocation',
        ),
    ]
