# Generated by Django 2.0.8 on 2019-12-20 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_address_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='citycustom',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='citycustom',
            name='country',
        ),
        migrations.RemoveField(
            model_name='citycustom',
            name='region',
        ),
        migrations.RemoveField(
            model_name='address',
            name='cityCustom',
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CityCustom',
        ),
    ]
