# Generated by Django 2.0.8 on 2019-12-23 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0007_auto_20191223_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant_address',
            name='merchant',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchant_address', to='portal.Merchant'),
        ),
    ]
