# Generated by Django 2.0.8 on 2019-12-23 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0008_auto_20191223_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant_address',
            name='state',
        ),
        migrations.AlterField(
            model_name='merchant_address',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.City'),
        ),
        migrations.AlterField(
            model_name='merchant_address',
            name='street_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='merchant_address',
            name='zip',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
