# Generated by Django 2.0.8 on 2019-08-31 22:59

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
