# Generated by Django 2.0.8 on 2019-12-23 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191223_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=25, verbose_name='Title'),
        ),
    ]
