# Generated by Django 2.0.8 on 2019-08-31 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='category',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Technology'), (2, 'Marketing')], db_index=True, default=None, null=True, verbose_name='Pick a time to schedule a over the phone consultation'),
        ),
    ]
