# Generated by Django 2.0.8 on 2019-08-31 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpage_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='category',
            field=models.CharField(blank=True, choices=[('TECHNOLOGY', 'Technology'), ('MARKETING', 'Marketing')], db_index=True, default=None, max_length=12, null=True),
        ),
    ]
