# Generated by Django 2.0.8 on 2019-08-31 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190831_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='category',
            field=models.CharField(blank=True, choices=[('Technology', 'TECHNOLOGY'), ('Marketing', 'MARKETING')], db_index=True, default=None, max_length=12, null=True),
        ),
    ]
