# Generated by Django 2.0.8 on 2019-09-01 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190831_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36)),
            ],
        ),
        migrations.AddField(
            model_name='blogpage',
            name='image',
            field=models.ImageField(help_text='All Images must be 800x600px', null=True, upload_to='blog_images/'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='tag',
            field=models.ManyToManyField(to='blog.Tag'),
        ),
    ]
