# Generated by Django 2.0.8 on 2020-01-04 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200104_0410'),
        ('blog', '0010_contact'),
    ]

    operations = [
    ]
