# Generated by Django 2.0.8 on 2020-01-15 01:11

import ckeditor_uploader.fields
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField()),
                ('subheader', models.TextField()),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('FOOD', 'Food'), ('VEHICLES', 'Automotive'), ('HOME', 'Home Improvement')], db_index=True, default='FOOD', max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(help_text='Image must be a .PNG or .JPG', upload_to='photos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('main_photo', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('image', models.ImageField(null=True, upload_to='photos/')),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('DR', 'Drafted'), ('PR', 'Published')], default='Drafted', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated at')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=64)),
                ('background', models.CharField(choices=[('bg-primary', 'primary'), ('bg-secondary', 'secondary'), ('bg-alt', 'alt')], default='Primary', max_length=12)),
                ('active', models.BooleanField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('slug', models.SlugField(unique=True)),
                ('business_name', models.CharField(max_length=100)),
                ('website_url', models.URLField(blank=True, max_length=500, null=True)),
                ('facebook_url', models.URLField(blank=True, max_length=500, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='store-logos/')),
                ('code_coupon', models.CharField(blank=True, help_text="This will be auto-generated as GEGOO####, if left blank. Set as 'NONE' if no coupon code is desired.", max_length=15, null=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, null=True, region=None)),
                ('postal_code', models.CharField(blank=True, max_length=12)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, help_text="Enter latitude of store's location.", max_digits=11, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, help_text="Enter longitude of store's location.", max_digits=11, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('downloadable_content_url', models.URLField(blank=True, help_text='Link to AWS download url goes here', max_length=500, null=True)),
                ('downloadable_content_title', models.CharField(blank=True, help_text='Examples: menu, brochure, etc.', max_length=500, null=True)),
                ('promotional_video_file_name', models.CharField(blank=True, help_text='Name of the file uploaded to Amazon S3 Bucket. (ie: Video.MP4)', max_length=1000)),
                ('promotional_video_thumbnail_name', models.CharField(blank=True, help_text='Name of the thumbnail image uploaded to Amazon S3 Bucket (USE .JPG NOT .PNG). (ie: Thumbnail.jpg)', max_length=1000)),
                ('ref_code', models.CharField(blank=True, editable=False, max_length=20, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated at')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Subcategories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('rating', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated at')),
            ],
        ),
    ]
