# Generated by Django 2.0.8 on 2020-01-04 21:30

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0008_city_timezone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=40, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Subcategories',
            },
        ),
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name_plural': 'Images'},
        ),
        migrations.RenameField(
            model_name='merchant',
            old_name='name',
            new_name='business_name',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='main_image',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='about',
            name='services_header',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='address',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='downloadable_content',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='ref_code',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='category',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='tag',
        ),
        migrations.AddField(
            model_name='merchant',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchant',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='portal.Category'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchant', to='cities_light.City'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='code_coupon',
            field=models.CharField(blank=True, help_text='NOTE: Leave blank and a GEGOO coupon code will be generated', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='downloadable_content_title',
            field=models.CharField(blank=True, help_text='Examples: menu, brochure, etc.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='downloadable_content_url',
            field=models.CharField(blank=True, help_text='Link to AWS download url goes here', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text="Enter latitude of merchant's location.", max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='merchant',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text="Enter longitude of merchant's location.", max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='promotional_video_file_name',
            field=models.CharField(blank=True, help_text='Name of the file uploaded to Amazon S3 Bucket. (ie: Video.MP4)', max_length=1000),
        ),
        migrations.AddField(
            model_name='merchant',
            name='promotional_video_thumbnail_name',
            field=models.CharField(blank=True, help_text='Name of the thumbnail image uploaded to Amazon S3 Bucket (USE .JPG NOT .PNG). (ie: Thumbnail.jpg)', max_length=1000),
        ),
        migrations.AddField(
            model_name='merchant',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offer',
            name='code_coupon',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='merchant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='portal.Merchant'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('FOOD', 'Food & Dining'), ('VEHICLES', 'Automotive & Transportation'), ('HOME', 'Home Improvement')], db_index=True, default='FOOD', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='about',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about', to='portal.About'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='facebook_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='website_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='offer',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='portal.Category'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='portal.Subcategory'),
        ),
    ]
