# Generated by Django 2.0.8 on 2019-09-22 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('IN PROGRESS', 'In Progress'), ('REQUIRES INPUT', 'Requires Input'), ('COMPLETED', 'Completed'), ('AWAITING PAYMENT', 'Awaiting Payment')], db_index=True, default='IN PROGRESS', max_length=16),
        ),
    ]
