# Generated by Django 2.0.8 on 2020-01-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20200104_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
