# Generated by Django 2.0.8 on 2020-01-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20200111_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
