# Generated by Django 2.0.8 on 2019-09-23 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20190922_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='job_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_transaction', to='portal.Job'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('IN PROGRESS', 'In Progress'), ('REQUIRES INPUT', 'Requires Input'), ('COMPLETED', 'Completed'), ('AWAITING PAYMENT', 'Awaiting Payment')], db_index=True, default='AWAITING PAYMENT', max_length=16),
        ),
    ]
