# Generated by Django 2.0.8 on 2018-10-18 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20181018_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='product',
            name='data',
        ),
        migrations.RemoveField(
            model_name='product',
            name='data_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='product',
            name='width_field',
        ),
    ]
