# Generated by Django 2.0.8 on 2020-01-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20200104_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
