# Generated by Django 2.0.8 on 2020-01-13 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_store_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('DR', 'Drafted'), ('PR', 'Published')], default='Drafted', max_length=50),
        ),
        migrations.AddField(
            model_name='store',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('N', 'Not Active')], default='Active', max_length=50),
        ),
    ]
