# Generated by Django 2.0.8 on 2019-09-23 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20190923_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='tax',
        ),
    ]
