# Generated by Django 2.0.8 on 2020-01-16 22:55

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20200116_0326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='store',
            name='location',
        ),
        migrations.RemoveField(
            model_name='store',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='code_coupon',
            field=models.CharField(blank=True, help_text="If left blank, this will be auto-generated as GEGOO####. Set as 'NONE' if no coupon code is desired for your store.", max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='offers',
            field=models.ManyToManyField(blank=True, to='portal.Offer'),
        ),
        migrations.AlterField(
            model_name='store',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, null=True, region='US'),
        ),
    ]
