# Generated by Django 2.0.8 on 2018-10-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20181018_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='height_field',
            field=models.IntegerField(default=255),
        ),
        migrations.AddField(
            model_name='product',
            name='width_field',
            field=models.IntegerField(default=255),
        ),
    ]
