# Generated by Django 2.0.8 on 2020-01-08 04:05

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cities_light', '0008_city_timezone'),
        ('location', '0003_auto_20200108_0405'),
        ('portal', '0005_auto_20200107_0319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateField(null=True)),
                ('active', models.BooleanField(default=False)),
                ('slug', models.SlugField(unique=True)),
                ('business_name', models.CharField(max_length=100)),
                ('website_url', models.URLField(blank=True, max_length=500, null=True)),
                ('facebook_url', models.URLField(blank=True, max_length=500, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='store-logos/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, null=True, region=None)),
                ('postal_code', models.CharField(blank=True, max_length=12)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, help_text="Enter latitude of store's location.", max_digits=11, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, help_text="Enter longitude of store's location.", max_digits=11, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('downloadable_content_url', models.URLField(blank=True, help_text='Link to AWS download url goes here', max_length=500, null=True)),
                ('downloadable_content_title', models.CharField(blank=True, help_text='Examples: menu, brochure, etc.', max_length=500, null=True)),
                ('promotional_video_file_name', models.CharField(blank=True, help_text='Name of the file uploaded to Amazon S3 Bucket. (ie: Video.MP4)', max_length=1000)),
                ('promotional_video_thumbnail_name', models.CharField(blank=True, help_text='Name of the thumbnail image uploaded to Amazon S3 Bucket (USE .JPG NOT .PNG). (ie: Thumbnail.jpg)', max_length=1000)),
                ('ref_code', models.CharField(blank=True, editable=False, max_length=20, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated at')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='portal.Category')),
                ('city', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='store', to='cities_light.City')),
            ],
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='about',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='category',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='city',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='code_coupon',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='merchant',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='status',
        ),
        migrations.AddField(
            model_name='offer',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
        migrations.AddField(
            model_name='offer',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offer',
            name='tag',
            field=models.ManyToManyField(blank=True, to='portal.Tag'),
        ),
        migrations.AddField(
            model_name='offer',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='offer',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.DeleteModel(
            name='Merchant',
        ),
        migrations.AddField(
            model_name='store',
            name='offers',
            field=models.ManyToManyField(to='portal.Offer'),
        ),
        migrations.AddField(
            model_name='store',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='portal.Subcategory'),
        ),
        migrations.AddField(
            model_name='store',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
