# Generated by Django 2.0.8 on 2020-01-17 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20200117_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='title',
            field=models.CharField(help_text='Company Slogan or catchy short description', max_length=50, null=True),
        ),
    ]
