# Generated by Django 2.0.8 on 2019-11-30 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20191130_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='services_header',
        ),
    ]
