# Generated by Django 2.0.8 on 2020-01-18 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_store_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='NOT APPROVED', max_length=20),
        ),
        migrations.AlterField(
            model_name='store',
            name='title',
            field=models.CharField(help_text='Company Slogan or catchy short description', max_length=40, null=True),
        ),
    ]
