# Generated by Django 2.0.8 on 2020-01-09 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20200108_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store', to='cities_light.City'),
        ),
    ]
