# Generated by Django 2.0.8 on 2020-01-09 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20200109_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='code_coupon',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
