# Generated by Django 2.0.8 on 2020-01-18 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20200118_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('DR', 'Being Reviewed'), ('PR', 'Published')], default='Drafted', max_length=50),
        ),
        migrations.AlterField(
            model_name='store',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='DR', max_length=20),
        ),
    ]
