# Generated by Django 2.0.8 on 2018-10-18 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='cost',
        ),
    ]
