# Generated by Django 2.0.8 on 2020-01-19 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20200118_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='DR', max_length=20),
        ),
    ]
