# Generated by Django 2.0.8 on 2019-11-30 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='portal.Category'),
        ),
    ]
