# Generated by Django 2.0.8 on 2020-01-10 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_store_code_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='code_coupon',
            field=models.CharField(blank=True, help_text="This will be auto-generated as GEGOO####, if left blank. Set as 'NONE' if no coupon code is desired.", max_length=15, null=True),
        ),
    ]
