# Generated by Django 2.0.8 on 2020-01-11 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_auto_20200110_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.SlugField(unique=True),
        ),
    ]
