# Generated by Django 2.0.8 on 2018-10-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_auto_20181018_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='group_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Basic'), (2, 'Premium'), (3, 'Organization')], db_index=True, default=1, verbose_name='Type'),
        ),
    ]
