# Generated by Django 2.0.8 on 2020-01-19 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_auto_20200119_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='DR', max_length=20),
        ),
    ]
