# Generated by Django 2.0.8 on 2020-01-11 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_auto_20200111_0549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='name',
            new_name='slug',
        ),
    ]
