# Generated by Django 2.0.8 on 2018-11-09 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_merchandise'),
        ('portal', '0011_course_lesson'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
