# Generated by Django 2.0.8 on 2020-01-11 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_auto_20200111_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='slug',
            new_name='name',
        ),
    ]
