# Generated by Django 2.0.8 on 2020-01-20 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_auto_20200119_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='DR', max_length=20),
        ),
    ]
