# Generated by Django 2.0.8 on 2019-11-30 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_auto_20191130_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchant',
            old_name='name',
            new_name='business_name',
        ),
    ]
