# Generated by Django 2.0.8 on 2018-11-12 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='membership_required',
            field=models.BooleanField(db_index=True, default=True, help_text='Does this course require a membership'),
        ),
    ]
