# Generated by Django 2.0.8 on 2020-01-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_auto_20200111_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
