# Generated by Django 2.0.8 on 2020-01-24 04:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_auto_20200124_0257'),
        ('portal', '0013_auto_20200124_0257'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionalVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('active', models.BooleanField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='files.VideoFile')),
            ],
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
        migrations.AlterField(
            model_name='store',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, default=1, help_text="Enter latitude of store's location.", max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.ImageField(null=True, upload_to='store-logos/'),
        ),
        migrations.AlterField(
            model_name='store',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, default=1, help_text="Enter longitude of store's location.", max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Being Reviewed'), (2, 'Published')], default=1),
        ),
    ]
