# Generated by Django 2.0.8 on 2018-11-24 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_course_membership_required'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
