# Generated by Django 2.0.8 on 2020-01-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_subcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
