# Generated by Django 2.0.8 on 2020-01-25 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_auto_20200124_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testimonial', to='portal.Store'),
        ),
    ]
