# Generated by Django 2.0.8 on 2019-01-02 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_auto_20190102_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='ordering_id',
            field=models.PositiveIntegerField(help_text='Ordering of courses to be displayed [Atleast one course must start at one]', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
