# Generated by Django 2.0.8 on 2019-01-02 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_auto_20190102_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='card_description',
            field=models.TextField(default='No Description', max_length=60),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
