# Generated by Django 2.0.8 on 2020-01-25 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_auto_20200125_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='title',
            field=models.CharField(default='', max_length=256),
        ),
    ]
