# Generated by Django 2.0.8 on 2019-12-06 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_auto_20191206_0158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchant',
            old_name='Longitude',
            new_name='longitude',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='lattitude',
        ),
        migrations.AddField(
            model_name='merchant',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text="Enter latitude of merchant's location.", max_digits=11, null=True),
        ),
    ]
