# Generated by Django 2.0.8 on 2019-01-05 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0017_auto_20190102_0308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(help_text='what did you think about this course?', max_length=255)),
                ('helpful', models.BooleanField(db_index=True, default=True, help_text='Was this ')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 Star'), (2, '2 Star'), (3, '3 Star'), (4, '4 Star'), (5, '5 Star')], db_index=True, default=5, verbose_name='Type')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_review', to='portal.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_review', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
