# Generated by Django 2.0.8 on 2019-01-05 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='course',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
