# Generated by Django 2.0.8 on 2020-02-01 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_auto_20200130_0303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotionalvideo',
            name='video',
        ),
        migrations.DeleteModel(
            name='PromotionalVideo',
        ),
    ]
