# Generated by Django 2.0.8 on 2020-01-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('FOOD', 'Food'), ('VEHICLES', 'Automotive'), ('HOME', 'Home Improvement')], db_index=True, default='FOOD', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
