# Generated by Django 2.0.8 on 2020-02-02 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_remove_store_city'),
        ('portal', '0019_auto_20200201_0614'),
    ]

    operations = [
    ]
