# Generated by Django 2.0.8 on 2020-01-11 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_auto_20200111_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Category'),
        ),
        migrations.AlterField(
            model_name='store',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_subcategory', to='portal.Subcategory'),
        ),
    ]
