# Generated by Django 2.0.8 on 2019-01-05 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0019_auto_20190105_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(help_text='what did you think about this course?', max_length=255)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], db_index=True, default=5, verbose_name='Rate this course between 1-5 stars.')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('review_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_review', to='portal.Course')),
                ('review_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_review', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
