# Generated by Django 2.0.8 on 2019-01-05 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_review', to='portal.Course'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_review', to=settings.AUTH_USER_MODEL),
        ),
    ]
