# Generated by Django 2.0.8 on 2020-02-02 00:33

import django.core.validators
from django.db import migrations, models
import portal.models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_merge_20200202_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.ImageField(null=True, upload_to='store-logos/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg']), portal.models.logo_file_size]),
        ),
    ]
