# Generated by Django 2.0.8 on 2020-01-12 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_auto_20200111_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Subcategory'),
        ),
    ]
