# Generated by Django 2.0.8 on 2020-01-14 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0021_auto_20200112_0158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='user',
            new_name='merchant',
        ),
    ]
