# Generated by Django 2.0.8 on 2020-02-02 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0021_auto_20200202_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='description',
        ),
        migrations.RemoveField(
            model_name='store',
            name='downloadable_content_title',
        ),
        migrations.RemoveField(
            model_name='store',
            name='downloadable_content_url',
        ),
        migrations.RemoveField(
            model_name='store',
            name='promotional_video_file_name',
        ),
        migrations.RemoveField(
            model_name='store',
            name='promotional_video_thumbnail_name',
        ),
    ]
