# Generated by Django 2.0.8 on 2019-12-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0021_auto_20191207_0817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='banner',
        ),
        migrations.AddField(
            model_name='merchant',
            name='promotional_video_thumbnail_name',
            field=models.CharField(blank=True, help_text='Name of the thumbnail image uploaded to Amazon S3 Bucket (USE .JPG NOT .PNG). (ie: Thumbnail.jpg)', max_length=1000),
        ),
    ]
