# Generated by Django 2.0.8 on 2019-01-05 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0022_auto_20190105_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_review', to='portal.Course'),
        ),
    ]
