# Generated by Django 2.0.8 on 2020-02-04 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0023_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='connections',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='current_user',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
