# Generated by Django 2.0.8 on 2020-02-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0023_auto_20200208_0141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='title',
        ),
        migrations.AddField(
            model_name='store',
            name='description',
            field=models.TextField(help_text='Describe the store', null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='slogan',
            field=models.CharField(help_text='Slogan or catchy short description', max_length=40, null=True),
        ),
    ]
