# Generated by Django 2.0.8 on 2019-01-06 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0024_auto_20190106_0339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_course',
        ),
        migrations.AddField(
            model_name='review',
            name='review_course',
            field=models.ManyToManyField(related_name='course_review', to='portal.Course'),
        ),
    ]
