# Generated by Django 2.0.8 on 2019-01-06 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0025_auto_20190106_0349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_course',
        ),
        migrations.AddField(
            model_name='review',
            name='review_course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_review', to='portal.Course'),
        ),
        migrations.RemoveField(
            model_name='review',
            name='review_user',
        ),
        migrations.AddField(
            model_name='review',
            name='review_user',
            field=models.ManyToManyField(related_name='user_review', to=settings.AUTH_USER_MODEL),
        ),
    ]
