# Generated by Django 2.0.8 on 2020-02-10 22:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0027_auto_20200210_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='valid_from',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Valid From'),
        ),
    ]
