# Generated by Django 2.0.8 on 2019-12-10 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0027_auto_20191210_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='address',
            field=models.ManyToManyField(related_name='merchant', to='portal.Address'),
        ),
    ]
