# Generated by Django 2.0.8 on 2019-01-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0027_auto_20190106_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.CharField(default='Math', help_text='Math, Science, English, etc.', max_length=30),
        ),
        migrations.AddField(
            model_name='course',
            name='targeted_grades',
            field=models.CharField(default='3rd Grade', help_text='3rd, 4th, 5th, etc.', max_length=45),
        ),
    ]
