# Generated by Django 2.0.8 on 2020-02-11 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0028_auto_20200210_2219'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
