# Generated by Django 2.0.8 on 2019-01-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0028_auto_20190106_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_content_1',
            field=models.CharField(default='Please Add a Description', help_text='Write a small paragraph about what this course offers', max_length=75),
        ),
        migrations.AddField(
            model_name='course',
            name='course_content_2',
            field=models.CharField(default='Please Add a Description', help_text='Write a small paragraph about what this course offers', max_length=75),
        ),
        migrations.AddField(
            model_name='course',
            name='course_content_3',
            field=models.CharField(default='Please Add a Description', help_text='Write a small paragraph about what this course offers', max_length=75),
        ),
        migrations.AddField(
            model_name='course',
            name='course_content_4',
            field=models.CharField(default='Please Add a Description', help_text='Write a small paragraph about what this course offers', max_length=75),
        ),
        migrations.AddField(
            model_name='course',
            name='course_content_5',
            field=models.CharField(default='Please Add a Description', help_text='Write a small paragraph about what this course offers', max_length=75),
        ),
        migrations.AddField(
            model_name='course',
            name='course_content_6',
            field=models.CharField(default='Please Add a Description', help_text='Write a small paragraph about what this course offers', max_length=75),
        ),
    ]
