# Generated by Django 2.0.8 on 2019-01-06 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0029_auto_20190106_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(help_text='This lesson is part of which course?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.Course'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='position',
            field=models.IntegerField(help_text='This represents the ordering of your lesson, if this is the first lesson of the course it should be 1.'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(help_text="This is what will be in the URL. Make it 'lesson-#' # represents the numbering ordering of the lesson, 1,2,3, etc."),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(help_text='Enter a name for this Course', max_length=120),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.CharField(help_text='Embed Video Link', max_length=200),
        ),
    ]
