# Generated by Django 2.0.8 on 2020-02-12 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0029_delete_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='store',
            name='offers',
        ),
        migrations.AddField(
            model_name='storeoffer',
            name='current_store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store', to='portal.Store'),
        ),
        migrations.AddField(
            model_name='storeoffer',
            name='offers',
            field=models.ManyToManyField(to='portal.Offer'),
        ),
    ]
