# Generated by Django 2.2.10 on 2020-02-25 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0026_auto_20200223_2246'),
        ('portal', '0030_auto_20200212_2222'),
    ]

    operations = [
    ]
