# Generated by Django 2.0.8 on 2019-01-06 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0030_auto_20190106_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.CharField(default='Please add a lesson description', help_text='Enter a short description', max_length=40),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(help_text="Make it 'lesson-#' # will equal the number you put in position. Such as 1,2,3,etc."),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(help_text='Enter a name for this Course', max_length=25),
        ),
    ]
