# Generated by Django 2.0.8 on 2019-01-07 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0031_auto_20190106_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='position',
        ),
        migrations.AddField(
            model_name='lesson',
            name='ordering_id',
            field=models.PositiveIntegerField(help_text='This represents the ordering of each individual lesson, if this is the first lesson of the course it should be 1.', null=True),
        ),
    ]
