# Generated by Django 2.0.8 on 2019-01-07 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0032_auto_20190107_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(help_text='This lesson is part of which course?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson', to='portal.Course'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(help_text="Use 'lesson-#' # will equal the number you put in position. Such as 1,2,3,etc."),
        ),
    ]
