# Generated by Django 2.2.10 on 2020-02-29 00:57

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0032_auto_20200228_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Example: 123 456-7890', max_length=20, null=True, region='US'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='updated_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Updated at'),
        ),
    ]
