# Generated by Django 2.0.8 on 2019-01-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0033_auto_20190107_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='document',
            field=models.FileField(blank=True, help_text='Upload PDF', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='lesson',
            name='powerpoint_link',
            field=models.CharField(blank=True, help_text='AWS Excel Download Link', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.CharField(help_text='AWS Embed Video Link', max_length=200),
        ),
    ]
