# Generated by Django 2.2.10 on 2020-03-04 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0033_auto_20200229_0057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='active',
            new_name='subscription_status',
        ),
    ]
