# Generated by Django 2.2.10 on 2020-03-04 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0034_auto_20200304_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='subscription_status',
            field=models.BooleanField(default=False),
        ),
    ]
