# Generated by Django 2.0.8 on 2019-01-24 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0034_auto_20190120_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='detailed_description',
            field=models.CharField(default='Please add a lesson description', help_text='Enter a long description explaining this course to the customer', max_length=500),
        ),
        migrations.AddField(
            model_name='lesson',
            name='image_url',
            field=models.CharField(help_text='AWS image url', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.CharField(help_text='AWS Video Link', max_length=200),
        ),
    ]
