# Generated by Django 2.0.8 on 2019-12-17 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0035_faq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='context',
        ),
    ]
