# Generated by Django 2.2.10 on 2020-03-11 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0035_auto_20200304_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeoffer',
            name='current_store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storeoffer', to='portal.Store'),
        ),
    ]
