# Generated by Django 2.0.8 on 2019-01-24 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0035_auto_20190124_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='image_url',
        ),
        migrations.AddField(
            model_name='course',
            name='image_url',
            field=models.CharField(help_text='AWS image url', max_length=500, null=True),
        ),
    ]
