# Generated by Django 2.0.8 on 2019-01-26 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0036_auto_20190124_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_thumbnail',
            field=models.CharField(help_text='Upload a .JPG', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='image_url',
            field=models.CharField(help_text='AWS image url. Dimensions: 600x400 Format: .JPG', max_length=500, null=True),
        ),
    ]
