# Generated by Django 2.2.10 on 2020-03-18 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0036_auto_20200311_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='street_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='zip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
