# Generated by Django 2.2.10 on 2020-03-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0037_auto_20200318_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Approval Reqiured'), (2, 'Published'), (3, 'Denied'), (4, 'Edit Pending')], default=1),
        ),
        migrations.AlterField(
            model_name='store',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Approval Reqiured'), (2, 'Published'), (3, 'Denied'), (4, 'Edit Pending')], default=1),
        ),
    ]
