# Generated by Django 2.2.10 on 2020-03-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0039_auto_20200326_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Draft'), (2, 'Published'), (3, 'Denied')], default=1),
        ),
        migrations.AlterField(
            model_name='store',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Draft'), (2, 'Published'), (3, 'Denied')], default=5),
        ),
    ]
