# Generated by Django 2.0.8 on 2019-12-23 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0039_merchant_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='address',
        ),
    ]
