# Generated by Django 2.0.8 on 2019-05-03 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0039_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_time',
            field=models.PositiveSmallIntegerField(choices=[(1, ''), (2, ''), (3, ''), (4, ''), (5, ''), (6, ''), (7, ''), (8, ''), (9, ''), (10, ''), (11, ''), (12, '')], db_index=True, default=None, verbose_name='Pick a time to schedule a over the phone consultation'),
        ),
    ]
