# Generated by Django 2.0.8 on 2020-01-04 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0040_merge_20191223_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='context',
        ),
        migrations.AddField(
            model_name='merchant',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Context',
        ),
        migrations.DeleteModel(
            name='FAQ',
        ),
    ]
