# Generated by Django 2.0.8 on 2020-01-04 17:41

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0008_city_timezone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0040_merge_20191223_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('business_name', models.CharField(max_length=100)),
                ('website_url', models.CharField(max_length=500)),
                ('facebook_url', models.CharField(max_length=500)),
                ('logo', models.ImageField(null=True, upload_to='merchant-logos/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('country', models.CharField(blank=True, max_length=40, unique=True)),
                ('state', models.CharField(blank=True, max_length=165)),
                ('postal_code', models.CharField(blank=True, max_length=12)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, help_text="Enter latitude of merchant's location.", max_digits=11, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, help_text="Enter longitude of merchant's location.", max_digits=11, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('downloadable_content_url', models.CharField(blank=True, help_text='Link to AWS download url goes here', max_length=500, null=True)),
                ('downloadable_content_title', models.CharField(blank=True, help_text='Examples: menu, brochure, etc.', max_length=500, null=True)),
                ('promotional_video_file_name', models.CharField(blank=True, help_text='Name of the file uploaded to Amazon S3 Bucket. (ie: Video.MP4)', max_length=1000)),
                ('promotional_video_thumbnail_name', models.CharField(blank=True, help_text='Name of the thumbnail image uploaded to Amazon S3 Bucket (USE .JPG NOT .PNG). (ie: Thumbnail.jpg)', max_length=1000)),
                ('ref_code', models.CharField(blank=True, editable=False, max_length=20, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated at')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='portal.Category')),
                ('city', models.ManyToManyField(related_name='merchant', to='cities_light.City')),
                ('merchant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='faq',
            name='context',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='about',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='category',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='city',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='merchant',
        ),
        migrations.AddField(
            model_name='offer',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
        migrations.AddField(
            model_name='offer',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Context',
        ),
        migrations.DeleteModel(
            name='FAQ',
        ),
        migrations.DeleteModel(
            name='Merchant',
        ),
        migrations.AddField(
            model_name='offer',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='portal.Store'),
        ),
    ]
