# Generated by Django 2.0.8 on 2020-01-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0041_auto_20200104_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='country',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
