# Generated by Django 2.2.10 on 2020-03-30 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0041_auto_20200329_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Draft'), (2, 'Pending'), (3, 'Published'), (4, 'Denied')], default=1),
        ),
        migrations.AlterField(
            model_name='store',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Draft'), (2, 'Pending'), (3, 'Published'), (4, 'Denied')], default=1),
        ),
    ]
