# Generated by Django 2.2.10 on 2020-03-30 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0042_auto_20200330_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='status',
        ),
    ]
