# Generated by Django 2.2.10 on 2020-04-02 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0043_remove_offer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Draft'), (3, 'Pending'), (2, 'Published'), (4, 'Denied')], default=1),
        ),
    ]
