# Generated by Django 2.0.8 on 2020-01-04 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0043_auto_20200104_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
