# Generated by Django 2.0.8 on 2020-01-04 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0044_auto_20200104_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
