# Generated by Django 2.2.10 on 2020-04-23 21:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0045_auto_20200423_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('ALL', 'All Services'), ('AUTO', 'Auto'), ('HYGIENE', 'Hygiene'), ('COMMUNITY', 'Community'), ('CONSTRUCTION', 'Construction'), ('FOOD', 'Food'), ('FUN', 'Fun'), ('GARDEN', 'Garden'), ('GROCERIES', 'Groceries'), ('HEALTH', 'Health'), ('HOME', 'Home Improvement'), ('PETS', 'Pets'), ('RETAIL', 'Retail'), ('PROFESSIONAL', 'Professional')], db_index=True, default='FOOD', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='store-logos/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='store',
            name='website_url',
            field=models.URLField(blank=True, help_text='Formatting requires HTTPS:// at the beginning. (ie. HTTPS://www.TheGegoo.com)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='storeoffer',
            name='offers',
            field=models.ManyToManyField(blank=True, to='portal.Offer'),
        ),
    ]
