# Generated by Django 2.0.8 on 2020-01-05 01:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0045_auto_20200104_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
