# Generated by Django 2.2.10 on 2020-04-25 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0046_auto_20200423_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('ALL', 'All Services'), ('AUTO', 'Auto'), ('BEAUTY', 'Health & Beauty'), ('COMMUNITY', 'Community'), ('CONSTRUCTION', 'Construction'), ('FOOD', 'Food'), ('FUN', 'Fun'), ('GARDEN', 'Garden'), ('GROCERIES', 'Groceries'), ('HOME', 'Home Improvement'), ('PETS', 'Pets'), ('RETAIL', 'Retail'), ('PROFESSIONAL', 'Professional')], db_index=True, default='FOOD', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='website_url',
            field=models.URLField(blank=True, help_text='Requires HTTPS:// at the beginning. (ie. HTTPS://www.TheGegoo.com)', max_length=500, null=True),
        ),
    ]
