# Generated by Django 2.0.8 on 2020-01-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0046_offer_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='store',
        ),
        migrations.AddField(
            model_name='store',
            name='offers',
            field=models.ManyToManyField(to='portal.Offer'),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
