# Generated by Django 2.2.10 on 2020-04-25 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0047_auto_20200425_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('ALL', 'All Services'), ('AUTO', 'Auto'), ('HEALTH-BEAUTY', 'Health & Beauty'), ('COMMUNITY', 'Community'), ('CONSTRUCTION', 'Construction'), ('FOOD', 'Food'), ('FUN', 'Fun'), ('GARDEN', 'Garden'), ('GROCERIES', 'Groceries'), ('HOME', 'Home Improvement'), ('PETS', 'Pets'), ('RETAIL', 'Retail'), ('PROFESSIONAL', 'Professional')], db_index=True, default='FOOD', max_length=20, unique=True),
        ),
    ]
