# Generated by Django 2.2.10 on 2020-04-26 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0048_auto_20200425_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='description',
            field=models.TextField(help_text='Describe the store', max_length=500, null=True),
        ),
    ]
