# Generated by Django 2.0.8 on 2020-01-05 21:00

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0049_auto_20200105_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='city',
            field=models.ManyToManyField(blank=True, related_name='merchant', to='cities_light.City'),
        ),
        migrations.AlterField(
            model_name='store',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, null=True, region=None),
        ),
    ]
