# Generated by Django 2.2.10 on 2020-04-26 00:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0049_auto_20200426_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.ImageField(blank=True, default='https://static-gegoo-bucket.s3.amazonaws.com/media-dev/store-logos/undraw_business_shop_qw5t.png?AWSAccessKeyId=AKIAXTP3WIX7E34PG34V&Signature=l46Xr%2FNe5GFaAjKZ3VdAbazDRaY%3D&Expires=1587863954', null=True, upload_to='store-logos/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
    ]
