# Generated by Django 2.0.8 on 2020-01-05 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0050_auto_20200105_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='downloadable_content_url',
            field=models.URLField(blank=True, help_text='Link to AWS download url goes here', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='website_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
